# Generated by Django 3.1.1 on 2020-10-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theatre_Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Release_year', models.IntegerField()),
                ('Genres', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=500)),
                ('Theatre', models.CharField(max_length=300)),
            ],
        ),
    ]
