# Generated by Django 3.1.1 on 2020-10-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TV_Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Release_year', models.IntegerField()),
                ('Genres', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=500)),
                ('Channel', models.CharField(max_length=300)),
            ],
        ),
    ]
